### ISSUE TITLE
Syncing encrypted notes to a cloud backup - will it work?

### ISSUE THREAD

**Issue by shankargopal** [Groomiac/CrocodileNote#1]
I have some notes in crocodilenote - the Android version - that are encrypted. I've been syncing these to an online cloud storage service. Will it be possible for me to restore them from there if my device or crocodilenote crashes or becomes inaccessible? If not, is there a way to make that possible? 

Many thanks for a great program!

**Comment by Groomiac** [comment]
Thanks for your interest in this app.

There are two things you have to do to restore all your content:
1) CrocodileNote will write the encrypted files to a directory on the SD card. If you copy this directory to the SD card on a new device, CrocodileNote will use it.
2) You have to backup the key file. That is in the internal app data folder for security reasons. In the main screen / start screen in the menu you can tap "Backup Secrets file". It will create a copy of the key file to the main folder of your SD card. Copy this as well (essential).

Summary:
If you perform steps 1+2 and you restart with a "blank" device, you do the following:
- You copy/sync you CrocodileNote folder to the SD card (delete existing ones)
- Start the app
- It will ask if you want to set up a key file or IMPORT one (you will use your backuped file)
- CrocodileNote will have your synced notes accessible again.

**Comment by shankargopal** [comment]
Thank you!  This is a great app.
