### ISSUE TITLE
aes encryption not possible?

### ISSUE THREAD

**Issue by rosc2112** [Groomiac/CrocodileNote#3]
I just got a replacement zte-817 phone running android 4.4.4. This new phone apparently removed support for AES; I get an error msg about 'eas encryption not possible on your device'   --  wtf? is there a way to enable or install aes on this or is just another example of US govt ballbusting crippling aes so they can spy on us?? =p

**Comment by Groomiac** [comment]
I think, it's something else. I added this error message at two places in the code (loading+creating the keyfile). As I look at it now, I do not know what could cause an exception  here, but it's surely not related to AES.
If you would have access to Android Studio oder adb logcat, you should be able to see a detailed stack trace...

I'm sorry, there is no easy solution to that.

**Comment by rosc2112** [comment]
Some more info after I had to do several resets: when I reset to factory defaults, I can import my key & notes just fine; after I update the phone's software through the system settings it gives that AES error and can't import.

But crocnote can create a new key. And but again, even though the new key uses the same password, ut can't open the old notes.

I'll try getting some useful debug info from adb.

I didn't make note of the default kernel # but the updated one is 

Linux version 3.4.0-gb9ccd38-00530-gfb048cc (xuzhenxuan@ztesuper25) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Tue Feb 7 00:47:0

**Comment by rosc2112** [comment]
Some more info after I had to do several resets: when I reset to factory defaults, I can import my key & notes just fine; after I update the phone's software through the system settings it gives that AES error and can't import.

But crocnote can create a new key. And but again, even though the new key uses the same password, ut can't open the old notes.

I'll try getting some useful debug info from adb.

I didn't make note of the default kernel # but the updated one is 

Linux version 3.4.0-gb9ccd38-00530-gfb048cc (xuzhenxuan@ztesuper25) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Tue Feb 7 00:47:0

**Comment by rosc2112** [comment]
Some more info after I had to do several resets: when I reset to factory defaults, I can import my key & notes just fine; after I update the phone's software through the system settings it gives that AES error and can't import.

But crocnote can create a new key. And but again, even though the new key uses the same password, ut can't open the old notes.

I'll try getting some useful debug info from adb.

I didn't make note of the default kernel # but the updated one is 

Linux version 3.4.0-gb9ccd38-00530-gfb048cc (xuzhenxuan@ztesuper25) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Tue Feb 7 00:47:0

**Comment by rosc2112** [comment]
sorry for the dupes, stupid phone.. and github gives me a 404 not found error when i try deleting them ;/

**Comment by Groomiac** [comment]
(no problem with the dupes ;)

I can't say much to the error without more info (stacktrace). It is strange!
The only thing I can think of right now is some SD card security twist ... in case you store the notes on the "external SD" - which had changed in Android over the years...

**Comment by Gatienzo** [comment]
I have the same problem on Android 13 Samsung phone. 
Every time I try to open it does that message and clases but if I try again it works.
Unfortunately this app it is not maintained. I liked it and have used for years.

**Comment by Groomiac** [comment]
I am sorry for that. I am still using the app myself but indeed have no time to maintain. That's why it's open-source. Hopefully someone will fork it. I never stumbled across this error on my own devices...
